export enum AccountResponseCode {
  OK = "ACCOUNT_OK",
  NOT_FOUND = "ACCOUNT_NOT_FOUND",
  LOCKED = "ACCOUNT_LOCKED",
  WRONG_PASSWORD = "ACCOUNT_WRONG_PASSWORD",
  SELF_LOCK = "ACCOUNT_SELF_LOCK",
}
