export enum AuthResponseCode {
  OK = "AUTH_OK",
  NOT_FOUND = "AUTH_NOT_FOUND",
  WRONG_PASSWORD = "AUTH_WRONG_PASSWORD",
  TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  TOKEN_REVOKED = "AUTH_TOKEN_REVOKED",
  USER_BLOCKED = "AUTH_USER_BLOCKED",
  FORBIDDEN = "AUTH_FORBIDDEN",
}
