export enum AuthResponseCode {
  OK = "AUTH_OK",
  NOT_FOUND = "AUTH_NOT_FOUND",
  WRONG_PASSWORD = "AUTH_WRONG_PASSWORD",
  FORBIDDEN = "AUTH_FORBIDDEN",
  USER_BLOCKED = "AUTH_USER_BLOCKED",
  EMAIL_EXIST = "AUTH_EMAIL_EXIST",
}
