export enum AuthResponseCode {
  OK = "AUTH_OK",
  SIGN_UP_WITH_GOOGLE = "AUTH_SIGN_UP_WITH_GOOGLE",
  NOT_FOUND = "AUTH_NOT_FOUND",
  WRONG_PASSWORD = "AUTH_WRONG_PASSWORD",
  FORBIDDEN = "AUTH_FORBIDDEN",
  USER_BLOCKED = "AUTH_USER_BLOCKED",
  EMAIL_EXIST = "AUTH_EMAIL_EXIST",
  INVALID_GOOGLE_TOKEN = "AUTH_INVALID_GOOGLE_TOKEN",
  TOO_MANY_LOGIN_ATTEMPTS = "AUTH_TOO_MANY_LOGIN_ATTEMPTS",
}
