export enum CategoryResponseCode {
  OK = "CTGR_OK",
  PARENT_NOT_FOUND = "CTGR_PARENT_NOT_FOUND",
  INVALID_PARENT = "CTGR_INVALID_PARENT",
  NOT_FOUND = "CTGR_NOT_FOUND",
  INVALID_LEVEL_EXCHANGE = "CTGR_INVALID_LEVEL_EXCHANGE",
}
