export enum JWTResponseCode {
  TOKEN_MISSING = "JWT_TOKEN_MISSING",
  INVALID_TOKEN = "JWT_INVALID_TOKEN",
  TOKEN_EXPIRED = "JWT_TOKEN_EXPIRED",
  TOKEN_REVOKED = "JWT_TOKEN_REVOKED",
  FAIL_VERIFY = "JWT_FAIL",
}
