export enum OrderResponseCode {
  OK = "ORDER_OK",
  INVALID_PRICE = "ORDER_INVALID_PRICE",
  NOT_FOUND = "ORDER_NOT_FOUND",
  INVALID_STATUS_CHANGE = "ORDER_INVALID_STATUS_CHANGE",
  FORBIDDEN = "ORDER_FORBIDDEN",
  TIMELINE_NOT_FOUND = "ORDER_TIMELINE_NOT_FOUND",
  ADDRESS_NOT_FOUND = "ORDER_ADDRESS_NOT_FOUND",
  INVALID_PRODUCT_QUANTITY = "ORDER_INVALID_PRODUCT_QUANTITY",
}
