export enum PaymentResponseCode {
  OK = "PAY_OK",
  NOT_FOUND = "PAY_NOT_FOUND",
  CONFIG_NOT_FOUND = "PAY_CONF_NOT_FOUND",
  PUBLIC_CONFIG_INVALID = "PAY_PUB_CONF_INVALID",
  PRIVATE_CONFIG_INVALID = "PAY_PRI_CONF_INVALID",
}
