export enum ProductResponseCode {
  OK = "PRODUCT_OK",
  FAIL = "PRODUCT_FAIL",
  CREATED = "PRODUCT_CREATED",
  UPDATED = "PRODUCT_UDPATED",
  CATEGORY_NOT_FOUND = "PROD_NOT_FOUND",
  INVALID_CATEGORY = "PROD_INVALID_CATEGORY",
  INVALID_ATTRIBUTE_VALUE = "PROD_INVALID_ATTR_VAL",
  POSTER_REQUIRED = "PROD_POSTER_REQUIRED",
  UNSUPPORTED_FILE = "PROD_UNSUPPORTED_FILE",
  OVERSIZE_FILE = "PROD_OVERSIZE_FILE",
  HAS_GAP_PRICE = "PROD_HAS_GAP_PRICE",
  NOT_FOUND = "PROD_NOT_FOUND",
}
