export enum SecurityAction {
  CONFIRM_CHANGE_EMAIL = "CONFIRM_CHANGE_EMAIL",
  REJECT_CHANGE_EMAIL = "REJECT_CHANGE_EMAIL",
  LOCK_ACCOUNT = "LOCK_ACCOUNT",
  ADMIN_CHANGE_PASSWORD = "ADMIN_CHANGE_PASSWORD",
}
