export enum OtpPurpose {
  VERIFY_EMAIL_REGISTER = "VERIFY_EMAIL_REGISTER",
  VERIFY_EMAIL_CHANGE_EMAIL = "VERIFY_EMAIL_CHANGE_EMAIL",
  VERIFY_EMAIL_ADMIN_CHANGE_EMAIL = "VERIFY_EMAIL_ADMIN_CHANGE_EMAIL",
}

export enum OtpChannel {
  EMAIL = "EMAIL",
}
