export const ROUTE = {
  home: "/",
  category: "/category",
  product: "",
  user: "/user",
  admin: "/",
  cart: "/cart",
  userAccount: "/account",
  userChangePassword: "/account/change-password",
  userOrder: "/account/order",
  userAddress: "/account/address",

  adminDashboard: "/",
  adminOrder: "/order",
  adminProduct: "/product",
  adminHighlight: "/highlight",
  adminCollection: "/collection",
  adminCategory: "/category",
  adminUser: "/user",
  adminLogin: "/login",
} as const;
