# ================================
# 1. Frontend (shop.com)
# ================================
server {
    listen 80;
    server_name devkon.click www.devkon.click;

    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    location /_next/static/ {
        proxy_pass http://frontend:3000;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }      
}

# ================================
# 2. Admin (admin.shop.com)
# ================================
server {
    listen 80;
    server_name admin.devkon.click;

    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# ================================
# 3. API (api.shop.com)
# ================================
server {
    listen 80;
    server_name api.devkon.click;

    location / {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# ================================
# 4. File server (file.shop.com)
# ================================
server {
    listen 80;
    server_name file.devkon.click;

    location / {
        alias /var/www/uploads/;
        autoindex off;

        expires 30d;
        add_header Cache-Control "public";
    }
}