import DOMPurify from "isomorphic-dompurify";
export function sanitizeHtml(html: string): string {
  return DOMPurify.sanitize(html);
  // return DOMPurify.sanitize(html, {
  //   ALLOWED_TAGS: [
  //     "b",
  //     "i",
  //     "em",
  //     "strong",
  //     "p",
  //     "ul",
  //     "ol",
  //     "li",
  //     "a",
  //     "br",
  //     "h1",
  //     "h2",
  //     "h3",
  //     "h4",
  //     "h5",
  //     "h6",
  //     "table",
  //     "thead",
  //     "tbody",
  //     "tr",
  //     "th",
  //     "td",
  //     "div",
  //     "span",
  //     "hr",
  //     "img",
  //   ],
  //   ALLOWED_ATTR: [
  //     "href",
  //     "target",
  //     "rel",
  //     "title",
  //     "style",
  //     "class",
  //     "id",
  //     "colspan",
  //     "rowspan",
  //     "align",
  //     "cellpadding",
  //     "cellspacing",
  //     "alt",
  //     "src",
  //     "title",
  //   ],
  // });
}
